"""S3 operations — S3Ops protocol for dependency injection."""

from __future__ import annotations
from typing import BinaryIO, Protocol


class S3Ops(Protocol):
    """Protocol defining the S3 client operations used by the upload module."""
    def put_object(self, Bucket: str, Key: str, Body: bytes | BinaryIO, ContentType: str) -> dict: ...
    def upload_fileobj(self, Fileobj: BinaryIO, Bucket: str, Key: str, Config: object) -> None: ...
    def head_object(self, Bucket: str, Key: str) -> dict | None: ...
    def get_paginator(self, name: str) -> object: ...
    def delete_object(self, Bucket: str, Key: str) -> None: ...
    def create_bucket(self, Bucket: str) -> None: ...
    def head_bucket(self, Bucket: str) -> None: ...
